In [87]:
import numpy as np,pandas as pd,matplotlib as plt #importing libraries

In [88]:
#importing data.csv file
DataSet = pd.read_csv('Machine Learning A-Z New\Part 1 - Data Preprocessing\Section 2 -------------------- Part 1 - Data Preprocessing --------------------\Data.csv')

In [89]:
#checking whether imported or not
DataSet

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [90]:
#now seperating Dependent and Independent varibles
X = DataSet.iloc[:,:-1].values #Independent variables
Y = DataSet.iloc[:,3].values  #Dependent Variables

In [91]:
X #checking

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [92]:
#checking
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [93]:
# Now we going to handle missing data 
# and we will take mean of data and place the mean in missing places and for that we have to include sklearn lib
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean', verbose = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [94]:
#checking missing values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [95]:
'''Now as our country column has names but our machine work only on numbers so to convert those we use label but it will 
create misunderstanding as it will give country name value to 0 1 2 and these values have relation which in reality country
name dont have like 0<1<2 so we will use columnTranformer and when we use column transformer we dont have to use label'''

from sklearn.compose import ColumnTransformer 
ct = ColumnTransformer([("Country", OneHotEncoder(),[0])], remainder="passthrough") # The last arg ([0]) is the list of columns you want to transform in this step
X = ct.fit_transform(X)
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [99]:
# Here we are usign labelEncoder to label yes and no in numbers and as y is dependent variable so machine will not get confused
#0<1 and other things like this
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [97]:
# Now we gonna split our dataset in 2 parts one train and other test
#for that we need library 

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)

In [98]:
#checking 
X_train

array([[0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [103]:
#  Now we will use scaling as in our data we have age and salary which are on different scale like we can see
# age is from 27-50 and salary is in 1000s and this will create problem as many of our algorithm work on Euclidean Distance
# Method (x2-x1)^2/(y2-y1)^2 so in that case the salary factor will destroy the age factor due to its scale so we going to 
# scale to make values in comparable scale

# There are 2 type of scaling 1 is Standardusation Xstand = (x-mean(x))/standard deviation(x)
# 2nd is normalisaiton Xnorm = (x-min(x))/max(x)-min(x)

# sometime algorithm dont use Euclidean distance but we we still scale as because of this algorithm converge very fastly

' Now we will use scaling as in our data we have age and salary which are on different scale like we can see\nage is from 27-50 and salary is in 1000s and this will create problem as many of our algorithm work on Euclidean Distance\nMethod (x2-x1)^2/(y2-y1)^2 so in that case the salary factor will destroy the age factor due to its scale so we going to \nscale to make values in comparable scale'

In [102]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test) #we dont have to fit test as it is already fit in trian section

# checking And everything is scaled between -1 and 1
X_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])