In [39]:
import numpy as np, matplotlib.pyplot as plt, pandas as pd

In [40]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [41]:
X = dataset.iloc[:,3:13].values # Taking only relavent inputs
Y = dataset.iloc[:,13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [42]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
#handling categorical data like geography and gender
ct = ColumnTransformer([("Geography", OneHotEncoder(),[1])], remainder="passthrough") # The last arg ([0]) is the list of columns you want to transform in this step
X = ct.fit_transform(X)
X = X[:,1:]
ct_2 = ColumnTransformer([("Gender", OneHotEncoder(),[3])], remainder="passthrough") # The last arg ([0]) is the list of columns you want to transform in this step
X = ct_2.fit_transform(X)
X = X[:,1:]
X[0:1,:]

array([[0.0, 0.0, 0.0, 619, 42, 2, 0.0, 1, 1, 1, 101348.88]], dtype=object)

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [44]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [45]:
classifier = Sequential()

In [46]:
#unit is number of nodes in hidden layer you choose it accroding to you or average of input and output dimension
# kernal_initializer is assigning initial weights and uniform means uniform number close to zero
#activation is activation function used in this hidden layer 
#input_dim is number of input or number of independent variable this is must argue for first hidden layer

classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))


C:\Users\verma\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [47]:
# 2nd hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))


In [48]:
# ouput layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))


In [49]:
#optimizer is algo you want to use for handling weights we using stochastic gradient
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [50]:
classifier.fit(X_train, Y_train, batch_size = 10, epochs = 70)


Epoch 1/70
8000/8000 [==============================] - 13s 2ms/step - loss: 0.4877 - accuracy: 0.7960
Epoch 2/70
8000/8000 [==============================] - 3s 427us/step - loss: 0.4292 - accuracy: 0.7960
Epoch 3/70
8000/8000 [==============================] - 3s 432us/step - loss: 0.4233 - accuracy: 0.7960
Epoch 4/70
8000/8000 [==============================] - 3s 429us/step - loss: 0.4190 - accuracy: 0.8207
Epoch 5/70
8000/8000 [==============================] - 3s 432us/step - loss: 0.4164 - accuracy: 0.8256
Epoch 6/70
8000/8000 [==============================] - 3s 431us/step - loss: 0.4145 - accuracy: 0.8310
Epoch 7/70
8000/8000 [==============================] - 3s 432us/step - loss: 0.4127 - accuracy: 0.8330
Epoch 8/70
8000/8000 [==============================] - 3s 431us/step - loss: 0.4120 - accuracy: 0.8321
Epoch 9/70
8000/8000 [==============================] - 3s 434us/step - loss: 0.4106 - accuracy: 0.8316
Epoch 10/70
8000/8000 [==============================] - 4s 444us

In [51]:
y_pred = classifier.predict(X_test) # This will give probabilities in y_pred
y_pred = (y_pred > 0.5) # This is will conver these prob in true and false so we can compare

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1550,   45],
       [ 277,  128]], dtype=int64)